### ISSUE TITLE
KeyError in split multi-allelic variant

### ISSUE THREAD

**Issue by danielmsk** [dbmi-bgm/mutanno#8]
```
Traceback (most recent call last):
  File "/miniconda3/bin/mutanno", line 8, in <module>
    sys.exit(cli())
  File "/miniconda3/lib/python3.6/site-packages/mutanno/__init__.py", line 22, in cli
    dispatch_job(opt)
  File "/miniconda3/lib/python3.6/site-packages/mutanno/__init__.py", line 39, in dispatch_job
    an.run()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 215, in run
    variant = self.vcfreader.get_variant()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 313, in get_variant
    self.liftover_hg38_hg19, infoheader=self.infoheader)
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 361, in __init__
    self.set_option()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 388, in set_option
    self.add_mutanno_infofield()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 420, in add_mutanno_infofield
    self.set_split_multiallelic_variant()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 478, in set_split_multiallelic_variant
    for record in vcf_util.split_multiallelic_variants(self.record):
  File "/miniconda3/lib/python3.6/site-packages/mutanno/util/vcf_util.py", line 210, in split_multiallelic_variants
    new_pl = get_biallelepl_multiallelepl('0/' + str(k+1), arr_pl)
  File "/miniconda3/lib/python3.6/site-packages/mutanno/util/vcf_util.py", line 253, in get_biallelepl_multiallelepl
    pidx = pl_pos_map['/'.join(ngt)]
KeyError: '0/1'
```

**Comment by danielmsk** [comment]
As the following example, the error occurs in the missing genotype.

```
chr3	94029349	.	ATTT	TTTT,A	1376.17	.
	AC=3,1;AF=0.750,0.250;AN=4;DP=40;ExcessHet=3.01;FS=0.000;MLEAC=3,1;MLEAF=0.750,0.250;MQ=57.93;QD=32.29;SOR=1.112
	GT:AD:DP:GQ:PGT:PID:PL:PS
	1/2:0,9,17:28:99:.:.:1276,929,901,349,0,290
	1/1:0,4,0:4:12:.:.:123,12,0,127,15,141
	.|.:0,0,0:.:.:1|0:94029301_CATAT_C:.:94029301
```

**Comment by danielmsk** [comment]
fixed. https://github.com/dbmi-bgm/mutanno/commit/3b4d987d31ed78ad9c362d7f37bffcc9b39f62ee
