### ISSUE TITLE
IndexError in split_multiallelic_variants function

### ISSUE THREAD

**Issue by danielmsk** [dbmi-bgm/mutanno#9]
```
Traceback (most recent call last):
  File "/miniconda3/bin/mutanno", line 8, in <module>
    sys.exit(cli())
  File "/miniconda3/lib/python3.6/site-packages/mutanno/__init__.py", line 22, in cli
    dispatch_job(opt)
  File "/miniconda3/lib/python3.6/site-packages/mutanno/__init__.py", line 39, in dispatch_job
    an.run()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 215, in run
    variant = self.vcfreader.get_variant()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 313, in get_variant
    self.liftover_hg38_hg19, infoheader=self.infoheader)
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 361, in __init__
    self.set_option()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 388, in set_option
    self.add_mutanno_infofield()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 420, in add_mutanno_infofield
    self.set_split_multiallelic_variant()
  File "/miniconda3/lib/python3.6/site-packages/mutanno/annotvcf.py", line 478, in set_split_multiallelic_variant
    for record in vcf_util.split_multiallelic_variants(self.record):
  File "/miniconda3/lib/python3.6/site-packages/mutanno/util/vcf_util.py", line 206, in split_multiallelic_variants
    arr[arrformat.index('DP')] = str(int(ad[0]) + int(ad[k+1]))
IndexError: list assignment index out of range
```

**Comment by danielmsk** [comment]
In the following line, the error occurs because the last column (./.:0,0,0) doesn't have DP field. 
```
chr1	4420293	.	ATGTGTG	*,A	188.97	.	AC=3,1;AF=0.750,0.250;AN=4;DP=31;ExcessHet=3.01;FS=0.000;MLEAC=3,1;MLEAF=0.750,0.250;MQ=52.57;QD=8.22;SOR=1.179;SAMPLEGENO=1/1|*/*|0/4/0|NA12877_sample,1/2|*/A|0/14/5|NA12878_sample,./.|./.|0/0/0|NA12879_sample	GT:AD:DP:GQ:PGT:PID:PL:PS	1|1:0,4,0:4:12:1|1:4420279_GTATATATATATATA_G:129,12,0,129,12,129:4420279	1/2:0,14,5:19:99:.:.:759,194,165,555,0,551	./.:0,0,0
```

**Comment by danielmsk** [comment]
fixed. https://github.com/dbmi-bgm/mutanno/commit/1183df3dc9a15d17383b13718dadce63e69766b8
